os: linux
language: go
go:
    - 1.14.x
services:
    - docker
script:
    - go test -v
    - echo "$DOCKER_PW" | docker login --username $DOCKER_USER --password-stdin
    - docker build -f Dockerfile -t $DOCKER_USER/demo:latest ./
    - GIT_SHA="$(git rev-parse --short HEAD)"
    - docker tag $DOCKER_USER/demo:latest $DOCKER_USER/demo:$GIT_SHA
    - docker push $DOCKER_USER/demo:latest
    - docker push $DOCKER_USER/demo:$GIT_SHA